// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NamPractice.API.Data;

#nullable disable

namespace Practice.API.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20251226075649_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NamPractice.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2a9e-3b4d-4f8a-9c2e-1a5b7d8e0f12"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("8a3d5c1e-7f4b-4e2a-8d9c-0f1a2b3c4d5e"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("9b2e4f7a-1c5d-4a8e-b0c3-6d7e8f1a2b34"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NamPractice.API.Models.Domain.Practice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInHours")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PracticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PracticeImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("NamPractice.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c3e5f7-2b4d-4a6e-9c8f-0d1e2b3a4c5d"),
                            Code = "NTH",
                            Name = "North"
                        },
                        new
                        {
                            Id = new Guid("b2d4f6a8-1c3e-4b5d-9f0e-7a8c1e2d3f4b"),
                            Code = "STH",
                            Name = "South"
                        },
                        new
                        {
                            Id = new Guid("d6b6a0e7-8b9c-9d0e-3f1a-6b7c8d9e0123"),
                            Code = "EST",
                            Name = "East"
                        },
                        new
                        {
                            Id = new Guid("c3e5a7b9-2d4f-4c6e-8a1b-0f2d3e4c5a6b"),
                            Code = "WST",
                            Name = "West"
                        });
                });

            modelBuilder.Entity("NamPractice.API.Models.Domain.Practice", b =>
                {
                    b.HasOne("NamPractice.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NamPractice.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
